pksunkara/cargo-workspaces

cargo-workspaces/src/utils/changable.rs, cargo-workspaces/src/utils/pkg.rs
This fixes #7, which was due to path separator mismatches.
=> Keep paths as Path for `ws changes`

cargo-workspaces/src/utils/cargo.rs
This also means that the tests can skip the `s/\r\n/\n/g` as they should stay as LF and not CRLF on every platform.
=> Detect line endings, don't assume platform

cargo-workspaces/src/init.rs, cargo-workspaces/src/main.rs, cargo-workspaces/src/utils/error.rs
This adds a new subcommand `init` to create a virtual workspace.
>  a [virtual workspace](https://doc.rust-lang.org/stable/cargo/reference/workspaces.html) is a workspace where the root Cargo.toml manifest does not define a package, and only lists the workspace members.
This can be useful to quickly setup a `Cargo.toml` at the root of a mono-repo that includes nested cargo packages somewhere in its tree.
Example:
For:
```
app
└── rust
├── cli
│   └── app
│       ├── Cargo.toml
│       └── src
│           └── main.rs
└── core
├── backend
│   ├── Cargo.toml
│   └── src
│       └── main.rs
└── command
├── Cargo.toml
└── src
└── main.rs
```
`cargo ws init` within the `app` directory will create the following `Cargo.toml` at `app/Cargo.toml`:
```
[workspace]
members = [
"rust/cli/app", …
```
=> Add init subcommand

README.md, cargo-workspaces/src/utils/changable.rs
Hi, sorry for the noise on #34. May I suggest a small documentation improvement? Though the current document is well-written, I feel the intention is even clearer if it has some more words about `--force` is an option to use when we want to include the unchanged crates. Feel free to close if you think this is redundant :) Thanks!
=> Explain --force a bit more clearly

cargo-workspaces/src/utils/version.rs
When confirming the versions in interactive mode, we should see the current crate version on the lhs instead of the current common version. Especially given that the current common version is already printed above and that independent packages show their individual versions.
```console
$ cargo ws version minor
info current common version 0.8.3
Changes:
- foo: 0.8.3 => 0.9.0
- bar: 0.1.2 => 0.9.0
- baz: 0.2.7 => 0.3.0
```
instead of
```console
$ cargo ws version minor
info current common version 0.8.3
Changes:
- foo: 0.8.3 => 0.9.0
- bar: 0.8.3 => 0.9.0
- baz: 0.2.7 => 0.3.0
```
=> version: display crate version over group version in preview

cargo-workspaces/src/create.rs, cargo-workspaces/tests/create.rs, cargo-workspaces/tests/snapshots/create__create_bin_2015.snap, cargo-workspaces/tests/snapshots/create__create_bin_2018.snap, cargo-workspaces/tests/snapshots/create__create_lib_2015.snap, cargo-workspaces/tests/snapshots/create__create_lib_2018.snap
Add additional arguments to the create subcommand that match the cargo options.  This adds support for running the create subcommand without prompts.  Add tests around the create subcommand.
This was added in preparation for new code to support --dry-run.  It simplifies testing around the create command and other commands that are destructive.
There are some design decisions here that may not match the rest of the application.
1. It doesn't use a mock library to do filesystem operations and cleans up the directory manually.
2. It's tied to the existing crate/package format, so may break on future changes to the cargo template projects.
Let me know what you think and if you have any changes.  Thanks for the work on the project, it's a great example of the power of clap.
=> Add support for running the create subcommand without prompts

cargo-workspaces/Cargo.toml
Apply workaround for hiding this warning
```console
$ cargo build
warning: /git/pksunkara/cargo-workspaces/cargo-workspaces/Cargo.toml: file found to be present in multiple build targets: /git/pksunkara/cargo-workspaces/cargo-workspaces/src/main.rs
```
Differing paths between targets tricks cargo into thinking they're different files, whereas when normalized, they're one and the same.
=> impl workaround for silencing build target redundancy warning

cargo-workspaces/tests/create.rs
I came across the following error while running tests in a clean chroot:
```
running 5 tests
test test_create_bin_2015 ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" }', tests/create.rs:51:30
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
FAILED
test test_create_bin_2018 ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" }', tests/create.rs:51:30
FAILED
test test_create_lib_2015 ... thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 39, kind: DirectoryNotEmpty, message: "Directory not empty" }', tests/create.rs:51:30
FAILED
test …
```
=> Clean up the git files during package tests

cargo-workspaces/Cargo.lock, cargo-workspaces/Cargo.toml, cargo-workspaces/src/main.rs
Currently if you hit ctrlc while using the interactive menu, the cursor will not show up, the issue is not solved upstream https://github.com/console-rs/dialoguer/issues/77 This is the available workaround
=> Restore the cursor after sigint

cargo-workspaces/Cargo.lock, cargo-workspaces/Cargo.toml
There's a bug in transitive dependency of `crates-index` which causes `cargo-workspaces` to panic. This bug is fixed in the latest `crates-index`.
I've stumbled upon a bug in older version of `crates-index`: it was using `smartstring` and causing the following fail in CI (see below).
Good news is that new version of `crates-index` uses `smol_string` instead. After updating `crates-index`, I no longer observe this bug.
Stack trace of `smartstring` panic:
```
thread 'main' panicked at 'assertion failed: len <= MAX_INLINE', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/smartstring-0.2.10/src/inline.rs:41:9
[229](https://github.com/fluencelabs/spell/actions/runs/4640402449/jobs/8212304491?pr=95#step:13:239)
stack backtrace: …
```
=> fix(deps)!: update crates-index to 0.19.7

cargo-workspaces/src/exec.rs, cargo-workspaces/tests/exec.rs, cargo-workspaces/tests/snapshots/exec__normal_ignore-2.snap, cargo-workspaces/tests/snapshots/exec__normal_ignore.snap
This uses similar logic to the `--ignore` in rename. It allows for a comma delimited list of ignores. We should probably update the other ignore to match this logic, maybe?
fixes: #97
=> add --ignore option to exec command

cargo-workspaces/src/publish.rs
Currently, the index is taken either from the first registry in the `publish` list of the `Cargo.toml` or from the crates.io index. However, if the `--registry` option is provided, it makes more sense to use the index from the provided registry.
This PR takes the index from the registry provided if the `--registry` option is set.
=> feat: Check appropriate registry for index when providing --registry option

cargo-workspaces/src/create.rs
Tries to solve this comment
https://github.com/pksunkara/cargo-workspaces/issues/46#issuecomment-1229234635
The basic idea is to reduce friction in using this tool by making the "specify an alternative package name" opt-in via optional command line arguments instead of requiring it.
There are two scenarios now that are new from the UX perspective:
1. There already exists a crate with the same name. In that case the rest of the workspace crate creation process will fail and clean up the mess, stating that a package with the given name exists. The user will be able to use the opt-in feature of passing `--name` on the command line to fix that up manually
2. Something else with the name inferring doesn't work out. I'm not even sure if that can be the case anymore, but `file_name` on paths …
=> feat: try to infer package name from path

cargo-workspaces/src/publish.rs
I use a private Cargo sparse registry. With the last two fixes, more stuff works, but overall there are still problems.
1. The current version asserts HTTP/2 is available. This can't be assumed, as while it's available for crates.io, it's not part of the registry spec. I've increased the scope of connection reuse so there should practically be no additional overhead (and arguably reduced due to fewer TLS handshakes).
1. http.cainfo is the cargo config which is used to set a new CA bundle. We utilise it because our company has its own trust root. This is not picked up by cargo-workspaces, so all commands fail with TLS issues. If this config is set, I've changed the code to configure the client to use it. This requires the use of rustls due to some quirks with reqwest.
1. Sparse registries …
=> Support http.cainfo and some authentication support

cargo-workspaces/src/create.rs
I am not sure which exact version of cargo this happens on but `create` command fails in cargo 1.78.0 because `Created` is not present in `stderr`. However, `Adding` is present as in this example - 
```text
❯ cargo new --name foo --lib --edition 2021 lib/foo
Creating library `foo` package
Adding `foo` as member of workspace at `/home/sushruth/code/moarr`
note: see more `Cargo.toml` keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
```
This PR tries to improve that check instead of crashing when there is no issue. (Fix for #153)
I am a beginner to rust so please help me make this fix better.
=> fix #153: create command now works with newer cargo versions

CHANGELOG.md, README.md, cargo-workspaces/Cargo.lock, cargo-workspaces/Cargo.toml, cargo-workspaces/src/changed.rs, cargo-workspaces/src/exec.rs, cargo-workspaces/src/list.rs, cargo-workspaces/src/main.rs, cargo-workspaces/src/plan.rs, cargo-workspaces/src/publish.rs, cargo-workspaces/src/utils/basic_checks.rs, cargo-workspaces/src/utils/cargo.rs, cargo-workspaces/src/utils/error.rs, cargo-workspaces/src/utils/list.rs, cargo-workspaces/src/utils/mod.rs, cargo-workspaces/src/utils/publish.rs
This PR adds two features I found useful recently:
- Ability to perform basic checks before running `cargo publish`.
- Ability to just print the packages in order in which they should be published.
The first one proved handy when I had to publish a lot of crates written by different people that weren't initially meant to be published. So every so often a field would be forgotten, but I won't know about it until I'm in the middle of the publishing process.
The second one is useful for large workspaces: crates.io has pretty strict rate limits on publishing new packages, so it's actually easier to get the order in which crates should be published and then do it manually.
=> feat: Implement print plan and basic checks for publish command

cargo-workspaces/src/main.rs
`cargo-workspaces` sets the `ctrl+c` handler that doesn't terminate the program. When working with large workspaces, I find myself having to kill it with sigterm instead of sigint. This PR fixes it.
Before:
```
$ cargo ws plan --skip-published
error: config value `http.cainfo` is not set
^C^C^C^C^C^C^C^C
[1]    8534 terminated  cargo ws plan --skip-published
```
After:
```
$ cargo ws plan --skip-published
error: config value `http.cainfo` is not set
^C%
```
=> Exit on ctrl+c

.github/workflows/ci.yml, cargo-workspaces/Cargo.toml, cargo-workspaces/src/exec.rs, cargo-workspaces/src/utils/publish.rs, cargo-workspaces/src/utils/version.rs, cargo-workspaces/tests/snapshots/create__create_bin_2015.snap, cargo-workspaces/tests/snapshots/create__create_bin_2018.snap, cargo-workspaces/tests/snapshots/create__create_lib_2015.snap, cargo-workspaces/tests/snapshots/create__create_lib_2018.snap, cargo-workspaces/tests/snapshots/create__member_glob.snap
Bumps MSRV to ~~1.79~~ 1.78. Two reasons:
1. 1.70 is too old, and [CI is broken](https://github.com/pksunkara/cargo-workspaces/actions/runs/10291338462/job/28483357538#step:5:268). At least 1.74 is required.
2. Output of `cargo` has changed, and it's better for tests to reflect the current state of affairs.
Changes were introduced in 1.78
Also fixes newly added clippy lints.
=> Bump MSRV to 1.78

cargo-workspaces/src/utils/publish.rs
I added a handler for tame_index::Error::NoCrateVersions, which raised the following error upon running `cargo workspaces publish` to an Azure Devops Artefacts registry when one of the workspace crates has not yet been published:: 
`error: crates index error: index entry contained no versions for the crate`
The proposed change results in an unpublished return value in the `is_published` function instead of an error. Publishing afterward is successful.
Tested successfully using  
`cargo workspaces publish --registry <...> --yes --all patch  --no-git-commit --token "$PAT"`
=> Fix workspace crate not in index error

cargo-workspaces/src/create.rs
not a lot of changes really. 
Just added 2024 to enum Edition in create.rs. 
I did test it, and it works, not thoroughly tested though.
=> added support for 2024 rust edition

CHANGELOG.md, README.md, cargo-workspaces/src/publish.rs
This commit introduces a new command-line option `--publish-interval` to the `publish` command. This option allows you to specify a number of seconds to wait between each crate publishing attempt. This helps prevent hitting API rate limits on a crate registry.
This commit also includes the following changes based on your feedback:
- Moved std imports to the top of the file in `cargo-workspaces/src/publish.rs`.
- Removed tests for the `--publish-interval` feature.
- Updated README.md to document the new option.
- Updated CHANGELOG.md with details of this new feature.
The implementation includes:
- Addition of the `--publish-interval <SECONDS>` argument to the `Publish` command.
- Logic in the `Publish::run` method to pause execution for the specified interval.
Addresses #177
=> feat: Add --publish-interval option and update documentation

cargo-workspaces/src/utils/version.rs
[68c7c5c](https://github.com/pksunkara/cargo-workspaces/commit/68c7c5cdea9d23ea1fc06829a3d47641b74db155#diff-19b0f79a9d400e60f00be959612d0e6bb4a21553d6ab295efc4ccf06b0641f5b) changed `get(<...>).is_none()` to `contains_key(...)`.
This inverts the result of the code: While the original checks whether the key is _absent_, the new version would check if the key is _present_.
This fix inverts the result of `contains_key` to restore the original behaviour.
I ran into this being an issue when updating the version of a workspace crate without any dependencies.
In this case, the crate would be skipped and the crate's `Cargo.toml` would not be updated.
=> Fix inverted logic from `68c7c5c`
